from __future__ import annotations

import json
from datetime import datetime


def glyph_template(
    case_name: str,
    solver: str,
    dim: str,
    boundaries: list[str],
    first_spacing: float,
    growth_rate: float,
) -> str:
    boundary_lines = "\n".join(f"    {name} {name}" for name in boundaries)

    return f"""# ============================================================
# GlyphForge Starter Script
# Case: {case_name}
# Solver target: {solver}
# Dimension: {dim}
#
# Purpose:
#   This is a beginner-friendly Pointwise Glyph starter script.
#   It documents boundary names and mesh parameters before export.
#
# Important:
#   v1 does not create a full production mesh automatically.
#   Use this file as a clean starting point inside Pointwise.
# ============================================================

package require PWI_Glyph

set CASE_NAME "{case_name}"
set SOLVER_TARGET "{solver}"
set DIMENSION "{dim}"

array set BOUNDARY_NAMES {{
{boundary_lines}
}}

array set MESH_PARAMS {{
    first_spacing {first_spacing}
    growth_rate {growth_rate}
}}

puts "GlyphForge starter loaded."
puts "Case name: $CASE_NAME"
puts "Solver target: $SOLVER_TARGET"
puts "Dimension: $DIMENSION"

puts ""
puts "Boundary names:"
foreach {{role name}} [array get BOUNDARY_NAMES] {{
    puts "  $role -> $name"
}}

puts ""
puts "Mesh parameters:"
puts "  first_spacing -> $MESH_PARAMS(first_spacing)"
puts "  growth_rate   -> $MESH_PARAMS(growth_rate)"

puts ""
puts "Next manual steps in Pointwise:"
puts "  1. Import or create geometry."
puts "  2. Create connectors/domains/blocks."
puts "  3. Apply boundary names consistently."
puts "  4. Check mesh quality."
puts "  5. Export mesh for SU2."
puts "  6. Use the same marker names in your SU2 config."

# Future GlyphForge versions can add:
#   - actual connector templates
#   - airfoil domain starter generation
#   - boundary condition assignment helpers
#   - mesh quality report helpers
#   - SU2 export helpers
"""


def mesh_parameters_json(
    case_name: str,
    solver: str,
    dim: str,
    boundaries: list[str],
    first_spacing: float,
    growth_rate: float,
) -> str:
    data = {
        "case_name": case_name,
        "created_by": "GlyphForge",
        "created_at_utc": datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "solver_target": solver,
        "dimension": dim,
        "boundaries": [
            {
                "role": name,
                "pointwise_name": name,
                "su2_marker": name,
            }
            for name in boundaries
        ],
        "mesh_parameters": {
            "first_spacing": first_spacing,
            "growth_rate": growth_rate,
            "notes": "Starter values only. Verify them for Reynolds number, y+, geometry scale, and solver setup.",
        },
    }

    return json.dumps(data, indent=2) + "\n"


def boundary_markdown(case_name: str, boundaries: list[str]) -> str:
    rows = "\n".join(f"| `{name}` | `{name}` | TODO |" for name in boundaries)

    return f"""# Boundary Names for `{case_name}`

Keep Pointwise boundary names and SU2 marker names consistent.

| Pointwise name | SU2 marker | Meaning |
|---|---|---|
{rows}

## Beginner reminder

If Pointwise exports a marker as `wall`, your SU2 config must also use `wall`.

Example:

```cfg
MARKER_EULER= ( wall )
MARKER_FAR= ( farfield )
```
"""


def workflow_markdown(case_name: str, solver: str, dim: str) -> str:
    return f"""# Mesh Workflow Notes: `{case_name}`

## Target

- Solver: `{solver}`
- Dimension: `{dim}`
- Toolchain: Pointwise/Glyph → mesh export → SU2 case setup

## Workflow

1. Define geometry.
2. Create connectors.
3. Create domains/blocks.
4. Apply boundary names.
5. Set mesh spacing and growth rate.
6. Check mesh quality.
7. Export mesh.
8. Use the same marker names in SU2.
9. Run SU2.
10. Inspect residuals and flowfield.

## Mesh quality checklist

- No negative cells.
- Boundary names are clear.
- Farfield is far enough from body.
- Wall spacing is documented.
- Growth rate is not too aggressive.
- Exported mesh opens correctly.
- SU2 config markers match exported mesh markers.

## Notes

Write your assumptions here:

```txt
Geometry:
Reynolds number:
Mach number:
Farfield distance:
Wall spacing:
Growth rate:
Mesh type:
Export format:
```
"""


def case_readme(case_name: str) -> str:
    return f"""# {case_name}

Generated by GlyphForge.

## Files

- `glyph/{case_name}_starter.glf` — Pointwise Glyph starter script
- `mesh/mesh_parameters.json` — documented mesh settings
- `su2/boundary_names.md` — SU2 marker naming notes
- `notes/workflow.md` — beginner mesh workflow checklist

## How to use

1. Open Pointwise.
2. Open or source the generated `.glf` script.
3. Follow the printed workflow notes.
4. Keep boundary names consistent with SU2.
"""